version: '3.8'

services:
  nginx-balancer:
    build: ./balancer/
    ports:
      - "8080:80"
    depends_on:
      - nginx-node-1
      - nginx-node-2
      - nginx-node-3
    networks: 
      - backend
      - frontend
  nginx-node-1:
    build: ./node/
    volumes:
      - ./node/site:/var/www/html
    networks: 
      - backend
  nginx-node-2:
    build: ./node/
    volumes:
      - ./node/site:/var/www/html
    networks: 
      - backend
  nginx-node-3:
    build: ./node/
    volumes:
      - ./node/site:/var/www/html
    networks: 
      - backend
networks:
  # The presence of these objects is sufficient to define them
  frontend: {}
  backend: {}