name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
# build image `containers07-base` from Dockerfile
      - name: Build the Docker image
        run: docker build -t containers07-base ./sample06
# Create container `test-container` for testing
      - name: Create `test-container`
        run: docker create --name test-container --volume database:/var/www/db containers07-base
# Copy tests to the container `test-container`
      - name: Copy tests to the container
        run: docker cp ./sample06/tests test-container:/var/www
# Run tests in the container `test-container`
      - name: Up the container
        run: docker start test-container
      - name: Run tests
        run: docker exec test-container php /var/www/html/tests/test.php
# Stop the container `test-container`
      - name: Stop the container
        run: docker stop test-container
# Remove the container `test-container`
      - name: Remove the container
        run: docker rm test-container
